### ISSUE TITLE
Unclear on where to run the generator

### ISSUE THREAD

**Issue by ngholbrook** [amanganiello90/generator-jhipster-electron#1]
* **Overview of the request**

It states to run the generator in a folder next to the application

* **Motivation for or Use Case** 

The instructions aren't very clear.  If I have a jhipster client app in a folder jhipster-client, do I create a new folder on the same level called jhipster-electron or do I create the folder inside the jhipster-client folder?

* **Suggest a Fix** 

Please clarify the location where this generator needs to be run from.

**Comment by ngholbrook** [comment]
Directory alongside your JHipster app leads me to believe outside the
JHipster app directory and create a new folder.  If I created a JHipster
app in /code/my-jhipster-app, it leads me to think I need to create a
folder /code/my-jhipster-electron and run from there.  This to me is
alongside.  I figured it out but I had some trial and error.

Top level inside the JHipster app folder would be more appropriate.  At
least for me.

Thanks for your work on this.

Nic

**Comment by amanganiello90** [comment]
Thanks a lot! I have updated [README.md](https://github.com/amanganiello90/generator-jhipster-electron/blob/develop/README.md):

> In the base directory of your JHipster app, run this module. This will create an electron-app folder that packages your war in exe.

**Comment by ngholbrook** [comment]
Thanks.  I know it was a small item but hopefully it will get more people
to use your plugin.  Thanks a lot for your efforts!

Nic

**Comment by amanganiello90** [comment]
Every feedback from the community is a pleasure for me. Thank you very much!
