### ISSUE TITLE
Starting using yo jhipster-electron

### ISSUE THREAD

**Issue by CBZakaria** [amanganiello90/generator-jhipster-electron#2]
Hello thanks for your contrubution

i'm having an issue while starting:
yo jhipster-electron

events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (---- node_modules\generator-jhipster-electron\generators\app\index.js:21:47)

Any suggestions ?

**Comment by amanganiello90** [comment]
HI @CBZakaria ,
maybe the error is the jhipster version installed. The module is old and compatible with jhipster 5.x.
I will update it with jhipster 6.6.0.

Thanks for the feedback!

**Comment by CBZakaria** [comment]
Thanks, do you think that will take time ? Need to know, to see if I'll use it in my project or search for alternatives

**Comment by amanganiello90** [comment]
> 
> 
> Thanks, do you think that will take time ? Need to know, to see if I'll use it in my project or search for alternatives

I will do in the next days. For jhipster 6.x it is created a jar file while this version use the war, so I have to update that.

**Comment by amanganiello90** [comment]
Hi @CBZakaria ,
Try to install the new [1.1.0 version](https://www.npmjs.com/package/generator-jhipster-electron/v/1.1.0).
Thanks for the issue, feel free to open new requests, you are welcome!
