### ISSUE TITLE
Gateway React app is not showing up in Electron

### ISSUE THREAD

**Issue by BDGHR** [amanganiello90/generator-jhipster-electron#4]
Hello,

Thank you for creating this package, it works great in getting an Electron distribution ready to test on Mac and Windows. I installed and ran the generator in the gateway, and built the jar in target with `./mvnw -Pprod clean verify`. Then I ran `npm run package` in the `electron-jar-package` directory. When I open the Mac jar application, I can hit F1 and see the log showing up. There are a few errors, but I would expect the gateway application to be visible at some point anyway (it never is).

What next steps would you suggest? I have already changed the port attribute in electron.app.config.json to different ones my application uses, and nothing works.

Thanks,
Grant (BDGHR)

**Comment by amanganiello90** [comment]
> Hello,
> 
> Thank you for creating this package, it works great in getting an Electron distribution ready to test on Mac and Windows. I installed and ran the generator in the gateway, and built the jar in target with `./mvnw -Pprod clean verify`. Then I ran `npm run package` in the `electron-jar-package` directory. When I open the Mac jar application, I can hit F1 and see the log showing up. There are a few errors, but I would expect the gateway application to be visible at some point anyway (it never is).
> 
> What next steps would you suggest? I have already changed the port attribute in electron.app.config.json to different ones my application uses, and nothing works.
> 
> Thanks,
> Grant (BDGHR)

Hey, thanks for the feedback, the pleasure is mine. But I don't understand the problem. What are the error shown in the log? How do you desire to works? Consider that you have built the jar with maven prod profile, so please attention to its configuration. Besides the electron port overwrite only the server.port property of your Java app, it can't change spring profile or other properties.

**Comment by BDGHR** [comment]
Thanks for the very fast response! Really the only error I see repeated is:
`org.h2.message.DbException: Log file error: "/target/h2db/db/orderofbattlegateway.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/target"" `

I am hoping this package packages up the whole gateway, including all of the Java and JavaScript code. The Java app seems to be running just fine, but the React app isn't displaying. Should I expect it to display?

Please let me know if I need to clarify further.

**Comment by amanganiello90** [comment]
Hi @BDGHR ,
your problem is that the gateway app is not in up ranning 'cause of your h2 db exception. So you can't visualize it in electron (without F1) or in localhost:YOUR_PORT. Have you ever try to run electron project with *npm start* ?

**Comment by BDGHR** [comment]
I have tried to run the project with `npm start` on my Mac and I get a different H2 error.

I am trying to run the Windows package with all the unpacked files at the moment. I did not understand that the .exe required the resources to read and use external files.

**Comment by amanganiello90** [comment]
Well, I explain with pleasure your doubts :) 
1. Your jhipster gateway is been created with h2db on disk. So your jar must read/write on the h2 trace file your data (that is under target folder of your project)
2. Electron package does not require external file. **It is your jar that requires external files**
3. Electron package on windows create a portable version, that is creates an **exe file** plus resource folder on your project. In that resource folder **there is your jar**. So when you open the exe file, it calls the jar that is in the resource folder (external of your exe).
4. In linux and Mac, maybe creates an **only file** (dvg for example). So your jar file is compressed and included in that file as a zip file. In this way, your app that has an h2 on disk configuration, can't write/read on file.

is all clear now? feel free for other questions :)

**Comment by BDGHR** [comment]
The good news is that by running the jhipster-registry on my Windows machine, I can run the Windows Electron build and see the application in the browser (actually opening up full Chrome) at the port I set in the config. Is there a reason I can't see the React application in the Electron window?

**Comment by amanganiello90** [comment]
So, that are problems with your app.. Could you give me the link of your jhipster project with electron module in order to test it?

**Comment by BDGHR** [comment]
I actually cannot because it's company confidential. Thank you for your help.

**Comment by BDGHR** [comment]
@amanganiello90 the <webview> tag seems to be deprecated in Electron >= 5.0. I used an Electron BrowserView set to my gateway React app's localhost port and got it to display the webapp in Electron.

https://www.electronjs.org/docs/api/webview-tag

**Comment by amanganiello90** [comment]
It not seems that it is used webview tag...
